name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Exercise-30
      id: exercise-30
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Exercise-30
        setup-command: mvn compile
        command: mvn test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCISE-30_RESULTS: "${{steps.exercise-30.outputs.result}}"
      with:
        runners: exercise-30
